<?php

namespace Academe\SagePay\PiSdk;

/**
 * CardIdentifiersTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Academe\SagePay\PiSdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * sagePay API Documentation
 *
 * $ref: 'description.md'
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.0.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

use PHPUnit\Framework\TestCase;

/**
 * CardIdentifiersTest Class Doc Comment
 *
 * @category    Class
 * @description CardIdentifiers
 * @package     Academe\SagePay\PiSdk
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class CardIdentifiersTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "CardIdentifiers"
     */
    public function testCardIdentifiers()
    {
    }

    /**
     * Test attribute "cardIdentifier"
     */
    public function testPropertyCardIdentifier()
    {
    }

    /**
     * Test attribute "expiry"
     */
    public function testPropertyExpiry()
    {
    }

    /**
     * Test attribute "cardType"
     */
    public function testPropertyCardType()
    {
    }
}
