<?php

namespace Academe\SagePay\PiSdk;

/**
 * InlineObject1Test
 *
 * PHP version 5
 *
 * @category Class
 * @package  Academe\SagePay\PiSdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * sagePay API Documentation
 *
 * $ref: 'description.md'
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.0.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

use PHPUnit\Framework\TestCase;

/**
 * InlineObject1Test Class Doc Comment
 *
 * @category    Class
 * @description InlineObject1
 * @package     Academe\SagePay\PiSdk
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class InlineObject1Test extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "InlineObject1"
     */
    public function testInlineObject1()
    {
    }

    /**
     * Test attribute "cardholderName"
     */
    public function testPropertyCardholderName()
    {
    }

    /**
     * Test attribute "cardNumber"
     */
    public function testPropertyCardNumber()
    {
    }

    /**
     * Test attribute "expiryDate"
     */
    public function testPropertyExpiryDate()
    {
    }

    /**
     * Test attribute "securityCode"
     */
    public function testPropertySecurityCode()
    {
    }
}
