<?php

namespace Academe\SagePay\PiSdk;

/**
 * ShippingDetailsTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Academe\SagePay\PiSdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * sagePay API Documentation
 *
 * $ref: 'description.md'
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.0.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

use PHPUnit\Framework\TestCase;

/**
 * ShippingDetailsTest Class Doc Comment
 *
 * @category    Class
 * @description The &#x60;shippingDetails&#x60; object is used to specify the shipping address details for a transaction. If not provided the values provided in the &#x60;billingAddress&#x60; object will be used for shipping information instead.
 * @package     Academe\SagePay\PiSdk
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class ShippingDetailsTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ShippingDetails"
     */
    public function testShippingDetails()
    {
    }

    /**
     * Test attribute "recipientFirstName"
     */
    public function testPropertyRecipientFirstName()
    {
    }

    /**
     * Test attribute "recipientLastName"
     */
    public function testPropertyRecipientLastName()
    {
    }

    /**
     * Test attribute "shippingAddress1"
     */
    public function testPropertyShippingAddress1()
    {
    }

    /**
     * Test attribute "shippingAddress2"
     */
    public function testPropertyShippingAddress2()
    {
    }

    /**
     * Test attribute "shippingCity"
     */
    public function testPropertyShippingCity()
    {
    }

    /**
     * Test attribute "shippingPostalCode"
     */
    public function testPropertyShippingPostalCode()
    {
    }

    /**
     * Test attribute "shippingCountry"
     */
    public function testPropertyShippingCountry()
    {
    }

    /**
     * Test attribute "shippingState"
     */
    public function testPropertyShippingState()
    {
    }
}
